/* cmdline.h */

/* File autogenerated by gengetopt version 2.13.1  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "Combiner"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * type_arg;	/* Data file type (default='pcl').  */
  char * method_arg;	/* Combination method (default='mean').  */
  char * output_arg;	/* Output file.  */
  int subset_arg;	/* Subset size (none if zero) (default='0').  */
  int skip_arg;	/* Columns to skip in input PCLs (default='2').  */
  int memmap_flag;	/* Memory map input files (default=off).  */
  int verbosity_arg;	/* Message verbosity (default='5').  */
  int normalize_flag;	/* Normalize inputs before combining (default=off).  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int type_given ;	/* Whether type was given.  */
  int method_given ;	/* Whether method was given.  */
  int output_given ;	/* Whether output was given.  */
  int subset_given ;	/* Whether subset was given.  */
  int skip_given ;	/* Whether skip was given.  */
  int memmap_given ;	/* Whether memmap was given.  */
  int verbosity_given ;	/* Whether verbosity was given.  */
  int normalize_given ;	/* Whether normalize was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);

extern char *type_values[] ;	/* Possible values for type.  */
extern char *method_values[] ;	/* Possible values for method.  */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
