/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  ..\gengetopt-2.13.1\Release\gengetopt.exe -N -e -i Data2DB.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->network_given = 0 ;
  args_info->input_given = 0 ;
  args_info->dir_in_given = 0 ;
  args_info->dir_out_given = 0 ;
  args_info->files_given = 0 ;
  args_info->memmap_given = 0 ;
  args_info->cache_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->block_files_given = 0 ;
  args_info->block_datasets_given = 0 ;
  args_info->buffer_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->network_arg = NULL;
  args_info->input_arg = NULL;
  args_info->dir_in_arg = gengetopt_strdup (".");
  args_info->dir_out_arg = gengetopt_strdup (".");
  args_info->files_arg = 1000 ;
  args_info->memmap_flag = 0;
  args_info->cache_flag = 0;
  args_info->verbosity_arg = 5 ;
  args_info->block_files_arg = -1 ;
  args_info->block_datasets_arg = 1 ;
  args_info->buffer_flag = 0;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Converts quantized DATs into compact database file collections");
  printf("\nUsage: Data2DB [OPTIONS]...\n\n");
  printf("%s\n","  -h, --help                Print help and exit");
  printf("%s\n","  -V, --version             Print version and exit");
  printf("%s\n","  -n, --network=filename    Input (X)DSL Bayes net");
  printf("%s\n","\nOptional:");
  printf("%s\n","  -i, --input=filename      Input gene mapping");
  printf("%s\n","  -d, --dir_in=directory    Data directory  (default=`.')");
  printf("%s\n","  -D, --dir_out=directory   Database directory  (default=`.')");
  printf("%s\n","  -f, --files=INT           Database file count  (default=`1000')");
  printf("%s\n","  -m, --memmap              Memory map input/output  (default=off)");
  printf("%s\n","  -c, --cache               Cache disk writes  (default=off)");
  printf("%s\n","  -v, --verbosity=INT       Message verbosity  (default=`5')");
  printf("%s\n","  -b, --block_files=INT     Number of database files per block  (default=`-1')");
  printf("%s\n","  -B, --block_datasets=INT  Number of datasets per block  (default=`1')");
  printf("%s\n","  -u, --buffer              Memory buffer disk writes  (default=off)");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  if (args_info->network_arg)
    {
      free (args_info->network_arg); /* free previous argument */
      args_info->network_arg = 0;
    }
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->dir_in_arg)
    {
      free (args_info->dir_in_arg); /* free previous argument */
      args_info->dir_in_arg = 0;
    }
  if (args_info->dir_out_arg)
    {
      free (args_info->dir_out_arg); /* free previous argument */
      args_info->dir_out_arg = 0;
    }
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  if (! args_info->network_given)
    {
      fprintf (stderr, "%s: '--network' ('-n') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "network",	1, NULL, 'n' },
        { "input",	1, NULL, 'i' },
        { "dir_in",	1, NULL, 'd' },
        { "dir_out",	1, NULL, 'D' },
        { "files",	1, NULL, 'f' },
        { "memmap",	0, NULL, 'm' },
        { "cache",	0, NULL, 'c' },
        { "verbosity",	1, NULL, 'v' },
        { "block_files",	1, NULL, 'b' },
        { "block_datasets",	1, NULL, 'B' },
        { "buffer",	0, NULL, 'u' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVn:i:d:D:f:mcv:b:B:u", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          if (local_args_info.version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->version_given && ! override)
            continue;
          local_args_info.version_given = 1;
          args_info->version_given = 1;
          cmdline_parser_free (&local_args_info);
          return 0;

        case 'n':	/* Input (X)DSL Bayes net.  */
          if (local_args_info.network_given)
            {
              fprintf (stderr, "%s: `--network' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->network_given && ! override)
            continue;
          local_args_info.network_given = 1;
          args_info->network_given = 1;
          if (args_info->network_arg)
            free (args_info->network_arg); /* free previous string */
          args_info->network_arg = gengetopt_strdup (optarg);
          break;

        case 'i':	/* Input gene mapping.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          break;

        case 'd':	/* Data directory.  */
          if (local_args_info.dir_in_given)
            {
              fprintf (stderr, "%s: `--dir_in' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dir_in_given && ! override)
            continue;
          local_args_info.dir_in_given = 1;
          args_info->dir_in_given = 1;
          if (args_info->dir_in_arg)
            free (args_info->dir_in_arg); /* free previous string */
          args_info->dir_in_arg = gengetopt_strdup (optarg);
          break;

        case 'D':	/* Database directory.  */
          if (local_args_info.dir_out_given)
            {
              fprintf (stderr, "%s: `--dir_out' (`-D') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dir_out_given && ! override)
            continue;
          local_args_info.dir_out_given = 1;
          args_info->dir_out_given = 1;
          if (args_info->dir_out_arg)
            free (args_info->dir_out_arg); /* free previous string */
          args_info->dir_out_arg = gengetopt_strdup (optarg);
          break;

        case 'f':	/* Database file count.  */
          if (local_args_info.files_given)
            {
              fprintf (stderr, "%s: `--files' (`-f') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->files_given && ! override)
            continue;
          local_args_info.files_given = 1;
          args_info->files_given = 1;
          args_info->files_arg = strtol (optarg,&stop_char,0);
          break;

        case 'm':	/* Memory map input/output.  */
          if (local_args_info.memmap_given)
            {
              fprintf (stderr, "%s: `--memmap' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->memmap_given && ! override)
            continue;
          local_args_info.memmap_given = 1;
          args_info->memmap_given = 1;
          args_info->memmap_flag = !(args_info->memmap_flag);
          break;

        case 'c':	/* Cache disk writes.  */
          if (local_args_info.cache_given)
            {
              fprintf (stderr, "%s: `--cache' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->cache_given && ! override)
            continue;
          local_args_info.cache_given = 1;
          args_info->cache_given = 1;
          args_info->cache_flag = !(args_info->cache_flag);
          break;

        case 'v':	/* Message verbosity.  */
          if (local_args_info.verbosity_given)
            {
              fprintf (stderr, "%s: `--verbosity' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbosity_given && ! override)
            continue;
          local_args_info.verbosity_given = 1;
          args_info->verbosity_given = 1;
          args_info->verbosity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'b':	/* Number of database files per block.  */
          if (local_args_info.block_files_given)
            {
              fprintf (stderr, "%s: `--block_files' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->block_files_given && ! override)
            continue;
          local_args_info.block_files_given = 1;
          args_info->block_files_given = 1;
          args_info->block_files_arg = strtol (optarg,&stop_char,0);
          break;

        case 'B':	/* Number of datasets per block.  */
          if (local_args_info.block_datasets_given)
            {
              fprintf (stderr, "%s: `--block_datasets' (`-B') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->block_datasets_given && ! override)
            continue;
          local_args_info.block_datasets_given = 1;
          args_info->block_datasets_given = 1;
          args_info->block_datasets_arg = strtol (optarg,&stop_char,0);
          break;

        case 'u':	/* Memory buffer disk writes.  */
          if (local_args_info.buffer_given)
            {
              fprintf (stderr, "%s: `--buffer' (`-u') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->buffer_given && ! override)
            continue;
          local_args_info.buffer_given = 1;
          args_info->buffer_given = 1;
          args_info->buffer_flag = !(args_info->buffer_flag);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
