/* cmdline.h */

/* File autogenerated by gengetopt version 2.13.1  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "Data2DB"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * network_arg;	/* Input (X)DSL Bayes net.  */
  char * input_arg;	/* Input gene mapping.  */
  char * dir_in_arg;	/* Data directory (default='.').  */
  char * dir_out_arg;	/* Database directory (default='.').  */
  int files_arg;	/* Database file count (default='1000').  */
  int memmap_flag;	/* Memory map input/output (default=off).  */
  int cache_flag;	/* Cache disk writes (default=off).  */
  int verbosity_arg;	/* Message verbosity (default='5').  */
  int block_files_arg;	/* Number of database files per block (default='-1').  */
  int block_datasets_arg;	/* Number of datasets per block (default='1').  */
  int buffer_flag;	/* Memory buffer disk writes (default=off).  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int network_given ;	/* Whether network was given.  */
  int input_given ;	/* Whether input was given.  */
  int dir_in_given ;	/* Whether dir_in was given.  */
  int dir_out_given ;	/* Whether dir_out was given.  */
  int files_given ;	/* Whether files was given.  */
  int memmap_given ;	/* Whether memmap was given.  */
  int cache_given ;	/* Whether cache was given.  */
  int verbosity_given ;	/* Whether verbosity was given.  */
  int block_files_given ;	/* Whether block_files was given.  */
  int block_datasets_given ;	/* Whether block_datasets was given.  */
  int buffer_given ;	/* Whether buffer was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
