/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  ../gengetopt-2.13.1/bin/gengetopt -N -e -i Dat2Dab.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->flip_given = 0 ;
  args_info->normalize_given = 0 ;
  args_info->zscore_given = 0 ;
  args_info->genes_given = 0 ;
  args_info->skip_given = 0 ;
  args_info->rank_given = 0 ;
  args_info->memmap_given = 0 ;
  args_info->cutoff_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->zero_given = 0 ;
  args_info->duplicates_given = 0 ;
  args_info->lookup1_given = 0 ;
  args_info->lookup2_given = 0 ;
  args_info->lookups_given = 0 ;
  args_info->remap_given = 0 ;
  args_info->genelist_given = 0 ;
  args_info->table_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_arg = NULL;
  args_info->output_arg = NULL;
  args_info->flip_flag = 0;
  args_info->normalize_flag = 0;
  args_info->zscore_flag = 0;
  args_info->genes_arg = NULL;
  args_info->skip_arg = 2 ;
  args_info->rank_flag = 0;
  args_info->memmap_flag = 0;
  args_info->verbosity_arg = 5 ;
  args_info->zero_flag = 0;
  args_info->duplicates_flag = 0;
  args_info->lookup1_arg = NULL;
  args_info->lookup2_arg = NULL;
  args_info->lookups_arg = NULL;
  args_info->remap_arg = NULL;
  args_info->genelist_flag = 0;
  args_info->table_flag = 0;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Text/binary data file interconversion");
  printf("\nUsage: Dat2Dab [OPTIONS]...\n\n");
  printf("%s\n","  -h, --help              Print help and exit");
  printf("%s\n","  -V, --version           Print version and exit");
  printf("%s\n","  -i, --input=filename    Input data file");
  printf("%s\n","  -o, --output=filename   Output data file");
  printf("%s\n","\nOptional:");
  printf("%s\n","  -f, --flip              Calculate one minus dat values  (default=off)");
  printf("%s\n","  -n, --normalize         Normalize to the range [0,1]  (default=off)");
  printf("%s\n","  -z, --zscore            Convert values to z-scores  (default=off)");
  printf("%s\n","  -g, --genes=filename    Process only genes from the given subset");
  printf("%s\n","  -s, --skip=INT          Columns to skip in input PCL  (default=`2')");
  printf("%s\n","  -r, --rank              Rank transform data  (default=off)");
  printf("%s\n","  -m, --memmap            Memory map input/output  (default=off)");
  printf("%s\n","  -c, --cutoff=DOUBLE     Exclude edges below cutoff");
  printf("%s\n","  -v, --verbosity=INT     Message verbosity  (default=`5')");
  printf("%s\n","  -e, --zero              Zero missing values  (default=off)");
  printf("%s\n","  -d, --duplicates        Allow dissimilar duplicate values  (default=off)");
  printf("%s\n","  -l, --lookup1=STRING    First lookup gene");
  printf("%s\n","  -L, --lookup2=STRING    Second lookup gene");
  printf("%s\n","  -t, --lookups=filename  Lookup gene set");
  printf("%s\n","  -p, --remap=filename    Gene name remapping file");
  printf("%s\n","  -G, --genelist          Only list genes  (default=off)");
  printf("%s\n","  -b, --table             Produce table formatted output  (default=off)");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->output_arg)
    {
      free (args_info->output_arg); /* free previous argument */
      args_info->output_arg = 0;
    }
  if (args_info->genes_arg)
    {
      free (args_info->genes_arg); /* free previous argument */
      args_info->genes_arg = 0;
    }
  if (args_info->lookup1_arg)
    {
      free (args_info->lookup1_arg); /* free previous argument */
      args_info->lookup1_arg = 0;
    }
  if (args_info->lookup2_arg)
    {
      free (args_info->lookup2_arg); /* free previous argument */
      args_info->lookup2_arg = 0;
    }
  if (args_info->lookups_arg)
    {
      free (args_info->lookups_arg); /* free previous argument */
      args_info->lookups_arg = 0;
    }
  if (args_info->remap_arg)
    {
      free (args_info->remap_arg); /* free previous argument */
      args_info->remap_arg = 0;
    }
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "flip",	0, NULL, 'f' },
        { "normalize",	0, NULL, 'n' },
        { "zscore",	0, NULL, 'z' },
        { "genes",	1, NULL, 'g' },
        { "skip",	1, NULL, 's' },
        { "rank",	0, NULL, 'r' },
        { "memmap",	0, NULL, 'm' },
        { "cutoff",	1, NULL, 'c' },
        { "verbosity",	1, NULL, 'v' },
        { "zero",	0, NULL, 'e' },
        { "duplicates",	0, NULL, 'd' },
        { "lookup1",	1, NULL, 'l' },
        { "lookup2",	1, NULL, 'L' },
        { "lookups",	1, NULL, 't' },
        { "remap",	1, NULL, 'p' },
        { "genelist",	0, NULL, 'G' },
        { "table",	0, NULL, 'b' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:o:fnzg:s:rmc:v:edl:L:t:p:Gb", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          if (local_args_info.version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->version_given && ! override)
            continue;
          local_args_info.version_given = 1;
          args_info->version_given = 1;
          cmdline_parser_free (&local_args_info);
          return 0;

        case 'i':	/* Input data file.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Output data file.  */
          if (local_args_info.output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_given && ! override)
            continue;
          local_args_info.output_given = 1;
          args_info->output_given = 1;
          if (args_info->output_arg)
            free (args_info->output_arg); /* free previous string */
          args_info->output_arg = gengetopt_strdup (optarg);
          break;

        case 'f':	/* Calculate one minus dat values.  */
          if (local_args_info.flip_given)
            {
              fprintf (stderr, "%s: `--flip' (`-f') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->flip_given && ! override)
            continue;
          local_args_info.flip_given = 1;
          args_info->flip_given = 1;
          args_info->flip_flag = !(args_info->flip_flag);
          break;

        case 'n':	/* Normalize to the range [0,1].  */
          if (local_args_info.normalize_given)
            {
              fprintf (stderr, "%s: `--normalize' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->normalize_given && ! override)
            continue;
          local_args_info.normalize_given = 1;
          args_info->normalize_given = 1;
          args_info->normalize_flag = !(args_info->normalize_flag);
          break;

        case 'z':	/* Convert values to z-scores.  */
          if (local_args_info.zscore_given)
            {
              fprintf (stderr, "%s: `--zscore' (`-z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->zscore_given && ! override)
            continue;
          local_args_info.zscore_given = 1;
          args_info->zscore_given = 1;
          args_info->zscore_flag = !(args_info->zscore_flag);
          break;

        case 'g':	/* Process only genes from the given subset.  */
          if (local_args_info.genes_given)
            {
              fprintf (stderr, "%s: `--genes' (`-g') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genes_given && ! override)
            continue;
          local_args_info.genes_given = 1;
          args_info->genes_given = 1;
          if (args_info->genes_arg)
            free (args_info->genes_arg); /* free previous string */
          args_info->genes_arg = gengetopt_strdup (optarg);
          break;

        case 's':	/* Columns to skip in input PCL.  */
          if (local_args_info.skip_given)
            {
              fprintf (stderr, "%s: `--skip' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->skip_given && ! override)
            continue;
          local_args_info.skip_given = 1;
          args_info->skip_given = 1;
          args_info->skip_arg = strtol (optarg,&stop_char,0);
          break;

        case 'r':	/* Rank transform data.  */
          if (local_args_info.rank_given)
            {
              fprintf (stderr, "%s: `--rank' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->rank_given && ! override)
            continue;
          local_args_info.rank_given = 1;
          args_info->rank_given = 1;
          args_info->rank_flag = !(args_info->rank_flag);
          break;

        case 'm':	/* Memory map input/output.  */
          if (local_args_info.memmap_given)
            {
              fprintf (stderr, "%s: `--memmap' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->memmap_given && ! override)
            continue;
          local_args_info.memmap_given = 1;
          args_info->memmap_given = 1;
          args_info->memmap_flag = !(args_info->memmap_flag);
          break;

        case 'c':	/* Exclude edges below cutoff.  */
          if (local_args_info.cutoff_given)
            {
              fprintf (stderr, "%s: `--cutoff' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->cutoff_given && ! override)
            continue;
          local_args_info.cutoff_given = 1;
          args_info->cutoff_given = 1;
          args_info->cutoff_arg = strtod (optarg, NULL);
          break;

        case 'v':	/* Message verbosity.  */
          if (local_args_info.verbosity_given)
            {
              fprintf (stderr, "%s: `--verbosity' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbosity_given && ! override)
            continue;
          local_args_info.verbosity_given = 1;
          args_info->verbosity_given = 1;
          args_info->verbosity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'e':	/* Zero missing values.  */
          if (local_args_info.zero_given)
            {
              fprintf (stderr, "%s: `--zero' (`-e') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->zero_given && ! override)
            continue;
          local_args_info.zero_given = 1;
          args_info->zero_given = 1;
          args_info->zero_flag = !(args_info->zero_flag);
          break;

        case 'd':	/* Allow dissimilar duplicate values.  */
          if (local_args_info.duplicates_given)
            {
              fprintf (stderr, "%s: `--duplicates' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->duplicates_given && ! override)
            continue;
          local_args_info.duplicates_given = 1;
          args_info->duplicates_given = 1;
          args_info->duplicates_flag = !(args_info->duplicates_flag);
          break;

        case 'l':	/* First lookup gene.  */
          if (local_args_info.lookup1_given)
            {
              fprintf (stderr, "%s: `--lookup1' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookup1_given && ! override)
            continue;
          local_args_info.lookup1_given = 1;
          args_info->lookup1_given = 1;
          if (args_info->lookup1_arg)
            free (args_info->lookup1_arg); /* free previous string */
          args_info->lookup1_arg = gengetopt_strdup (optarg);
          break;

        case 'L':	/* Second lookup gene.  */
          if (local_args_info.lookup2_given)
            {
              fprintf (stderr, "%s: `--lookup2' (`-L') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookup2_given && ! override)
            continue;
          local_args_info.lookup2_given = 1;
          args_info->lookup2_given = 1;
          if (args_info->lookup2_arg)
            free (args_info->lookup2_arg); /* free previous string */
          args_info->lookup2_arg = gengetopt_strdup (optarg);
          break;

        case 't':	/* Lookup gene set.  */
          if (local_args_info.lookups_given)
            {
              fprintf (stderr, "%s: `--lookups' (`-t') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookups_given && ! override)
            continue;
          local_args_info.lookups_given = 1;
          args_info->lookups_given = 1;
          if (args_info->lookups_arg)
            free (args_info->lookups_arg); /* free previous string */
          args_info->lookups_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* Gene name remapping file.  */
          if (local_args_info.remap_given)
            {
              fprintf (stderr, "%s: `--remap' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->remap_given && ! override)
            continue;
          local_args_info.remap_given = 1;
          args_info->remap_given = 1;
          if (args_info->remap_arg)
            free (args_info->remap_arg); /* free previous string */
          args_info->remap_arg = gengetopt_strdup (optarg);
          break;

        case 'G':	/* Only list genes.  */
          if (local_args_info.genelist_given)
            {
              fprintf (stderr, "%s: `--genelist' (`-G') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genelist_given && ! override)
            continue;
          local_args_info.genelist_given = 1;
          args_info->genelist_given = 1;
          args_info->genelist_flag = !(args_info->genelist_flag);
          break;

        case 'b':	/* Produce table formatted output.  */
          if (local_args_info.table_given)
            {
              fprintf (stderr, "%s: `--table' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->table_given && ! override)
            continue;
          local_args_info.table_given = 1;
          args_info->table_given = 1;
          args_info->table_flag = !(args_info->table_flag);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
