/*
  File autogenerated by gengetopt version 2.22
  generated with the following command:
  /memex/qzhu/usr/bin/gengetopt -iMutualRanker.ggo --default-optional -u -N -e 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Calculates gene order by mutual rank";

const char *gengetopt_args_info_usage = "Usage: MutualRanker [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --input=filename          Input gene map  (default=`NA')",
  "  -f, --convert_rank            Convert to rank  (default=off)",
  "  -c, --output_component        Output component weighting, gene score. Creates \n                                  *.gscore_comp. Used with Query mode  \n                                  (default=off)",
  "  -m, --merge_component         Merge component (generated from *.gscore_comp)  \n                                  (default=off)",
  "\nMerge mode:",
  "  -n, --merge_gscore_list=filename\n                                Merge gscore list (for merge), contains a list \n                                  of .gscore_comp files with path  \n                                  (default=`NA')",
  "\nConvert mode:",
  "  -g, --input_file=filename     Input DAB file (for convert)  (default=`NA')",
  "  -r, --output_rank_file=filename\n                                Output DAB with rank information (for convert)  \n                                  (default=`NA')",
  "\nQuery mode:",
  "  -q, --query=filename          Query file  (default=`NA')",
  "  -t, --tdab_list=filename      Dab list (input)  (default=`NA')",
  "  -d, --dab_dir=directory       Dab directory (input)",
  "  -Z, --threshold_q=FLOAT       Fraction of query genes need to be present in a \n                                  dataset  (default=`0')",
  "  -Y, --threshold_g=FLOAT       Fraction of datasets that must contain a gene \n                                  to put it in ranking (important if individual \n                                  datasets have very different gene coverage, \n                                  and for datasets with small gene-size)  \n                                  (default=`0.50')",
  "  -S, --search_mode=STRING      Search mode: equal weighted (eq) or CV LOI \n                                  (cv_loi).  (possible values=\"eq\", \n                                  \"cv_loi\", \"NA\" default=`NA')",
  "  -D, --dir_out=directory       Output directory",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


char *cmdline_parser_search_mode_values[] = {"eq", "cv_loi", "NA", 0} ;	/* Possible values for search_mode.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->convert_rank_given = 0 ;
  args_info->output_component_given = 0 ;
  args_info->merge_component_given = 0 ;
  args_info->merge_gscore_list_given = 0 ;
  args_info->input_file_given = 0 ;
  args_info->output_rank_file_given = 0 ;
  args_info->query_given = 0 ;
  args_info->tdab_list_given = 0 ;
  args_info->dab_dir_given = 0 ;
  args_info->threshold_q_given = 0 ;
  args_info->threshold_g_given = 0 ;
  args_info->search_mode_given = 0 ;
  args_info->dir_out_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_arg = gengetopt_strdup ("NA");
  args_info->input_orig = NULL;
  args_info->convert_rank_flag = 0;
  args_info->output_component_flag = 0;
  args_info->merge_component_flag = 0;
  args_info->merge_gscore_list_arg = gengetopt_strdup ("NA");
  args_info->merge_gscore_list_orig = NULL;
  args_info->input_file_arg = gengetopt_strdup ("NA");
  args_info->input_file_orig = NULL;
  args_info->output_rank_file_arg = gengetopt_strdup ("NA");
  args_info->output_rank_file_orig = NULL;
  args_info->query_arg = gengetopt_strdup ("NA");
  args_info->query_orig = NULL;
  args_info->tdab_list_arg = gengetopt_strdup ("NA");
  args_info->tdab_list_orig = NULL;
  args_info->dab_dir_arg = NULL;
  args_info->dab_dir_orig = NULL;
  args_info->threshold_q_arg = 0;
  args_info->threshold_q_orig = NULL;
  args_info->threshold_g_arg = 0.50;
  args_info->threshold_g_orig = NULL;
  args_info->search_mode_arg = gengetopt_strdup ("NA");
  args_info->search_mode_orig = NULL;
  args_info->dir_out_arg = NULL;
  args_info->dir_out_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->convert_rank_help = gengetopt_args_info_help[3] ;
  args_info->output_component_help = gengetopt_args_info_help[4] ;
  args_info->merge_component_help = gengetopt_args_info_help[5] ;
  args_info->merge_gscore_list_help = gengetopt_args_info_help[7] ;
  args_info->input_file_help = gengetopt_args_info_help[9] ;
  args_info->output_rank_file_help = gengetopt_args_info_help[10] ;
  args_info->query_help = gengetopt_args_info_help[12] ;
  args_info->tdab_list_help = gengetopt_args_info_help[13] ;
  args_info->dab_dir_help = gengetopt_args_info_help[14] ;
  args_info->threshold_q_help = gengetopt_args_info_help[15] ;
  args_info->threshold_g_help = gengetopt_args_info_help[16] ;
  args_info->search_mode_help = gengetopt_args_info_help[17] ;
  args_info->dir_out_help = gengetopt_args_info_help[18] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->merge_gscore_list_arg));
  free_string_field (&(args_info->merge_gscore_list_orig));
  free_string_field (&(args_info->input_file_arg));
  free_string_field (&(args_info->input_file_orig));
  free_string_field (&(args_info->output_rank_file_arg));
  free_string_field (&(args_info->output_rank_file_orig));
  free_string_field (&(args_info->query_arg));
  free_string_field (&(args_info->query_orig));
  free_string_field (&(args_info->tdab_list_arg));
  free_string_field (&(args_info->tdab_list_orig));
  free_string_field (&(args_info->dab_dir_arg));
  free_string_field (&(args_info->dab_dir_orig));
  free_string_field (&(args_info->threshold_q_orig));
  free_string_field (&(args_info->threshold_g_orig));
  free_string_field (&(args_info->search_mode_arg));
  free_string_field (&(args_info->search_mode_orig));
  free_string_field (&(args_info->dir_out_arg));
  free_string_field (&(args_info->dir_out_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->convert_rank_given)
    write_into_file(outfile, "convert_rank", 0, 0 );
  if (args_info->output_component_given)
    write_into_file(outfile, "output_component", 0, 0 );
  if (args_info->merge_component_given)
    write_into_file(outfile, "merge_component", 0, 0 );
  if (args_info->merge_gscore_list_given)
    write_into_file(outfile, "merge_gscore_list", args_info->merge_gscore_list_orig, 0);
  if (args_info->input_file_given)
    write_into_file(outfile, "input_file", args_info->input_file_orig, 0);
  if (args_info->output_rank_file_given)
    write_into_file(outfile, "output_rank_file", args_info->output_rank_file_orig, 0);
  if (args_info->query_given)
    write_into_file(outfile, "query", args_info->query_orig, 0);
  if (args_info->tdab_list_given)
    write_into_file(outfile, "tdab_list", args_info->tdab_list_orig, 0);
  if (args_info->dab_dir_given)
    write_into_file(outfile, "dab_dir", args_info->dab_dir_orig, 0);
  if (args_info->threshold_q_given)
    write_into_file(outfile, "threshold_q", args_info->threshold_q_orig, 0);
  if (args_info->threshold_g_given)
    write_into_file(outfile, "threshold_g", args_info->threshold_g_orig, 0);
  if (args_info->search_mode_given)
    write_into_file(outfile, "search_mode", args_info->search_mode_orig, cmdline_parser_search_mode_values);
  if (args_info->dir_out_given)
    write_into_file(outfile, "dir_out", args_info->dir_out_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "convert_rank",	0, NULL, 'f' },
        { "output_component",	0, NULL, 'c' },
        { "merge_component",	0, NULL, 'm' },
        { "merge_gscore_list",	1, NULL, 'n' },
        { "input_file",	1, NULL, 'g' },
        { "output_rank_file",	1, NULL, 'r' },
        { "query",	1, NULL, 'q' },
        { "tdab_list",	1, NULL, 't' },
        { "dab_dir",	1, NULL, 'd' },
        { "threshold_q",	1, NULL, 'Z' },
        { "threshold_g",	1, NULL, 'Y' },
        { "search_mode",	1, NULL, 'S' },
        { "dir_out",	1, NULL, 'D' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVi:fcmn:g:r:q:t:d:Z:Y:S:D:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "version", 'V',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'i':	/* Input gene map.  */
        
        
          if (update_arg( (void *)&(args_info->input_arg), 
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Convert to rank.  */
        
        
          if (update_arg((void *)&(args_info->convert_rank_flag), 0, &(args_info->convert_rank_given),
              &(local_args_info.convert_rank_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "convert_rank", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Output component weighting, gene score. Creates *.gscore_comp. Used with Query mode.  */
        
        
          if (update_arg((void *)&(args_info->output_component_flag), 0, &(args_info->output_component_given),
              &(local_args_info.output_component_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "output_component", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Merge component (generated from *.gscore_comp).  */
        
        
          if (update_arg((void *)&(args_info->merge_component_flag), 0, &(args_info->merge_component_given),
              &(local_args_info.merge_component_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "merge_component", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Merge gscore list (for merge), contains a list of .gscore_comp files with path.  */
        
        
          if (update_arg( (void *)&(args_info->merge_gscore_list_arg), 
               &(args_info->merge_gscore_list_orig), &(args_info->merge_gscore_list_given),
              &(local_args_info.merge_gscore_list_given), optarg, 0, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "merge_gscore_list", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Input DAB file (for convert).  */
        
        
          if (update_arg( (void *)&(args_info->input_file_arg), 
               &(args_info->input_file_orig), &(args_info->input_file_given),
              &(local_args_info.input_file_given), optarg, 0, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input_file", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Output DAB with rank information (for convert).  */
        
        
          if (update_arg( (void *)&(args_info->output_rank_file_arg), 
               &(args_info->output_rank_file_orig), &(args_info->output_rank_file_given),
              &(local_args_info.output_rank_file_given), optarg, 0, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output_rank_file", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Query file.  */
        
        
          if (update_arg( (void *)&(args_info->query_arg), 
               &(args_info->query_orig), &(args_info->query_given),
              &(local_args_info.query_given), optarg, 0, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "query", 'q',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Dab list (input).  */
        
        
          if (update_arg( (void *)&(args_info->tdab_list_arg), 
               &(args_info->tdab_list_orig), &(args_info->tdab_list_given),
              &(local_args_info.tdab_list_given), optarg, 0, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "tdab_list", 't',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Dab directory (input).  */
        
        
          if (update_arg( (void *)&(args_info->dab_dir_arg), 
               &(args_info->dab_dir_orig), &(args_info->dab_dir_given),
              &(local_args_info.dab_dir_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "dab_dir", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'Z':	/* Fraction of query genes need to be present in a dataset.  */
        
        
          if (update_arg( (void *)&(args_info->threshold_q_arg), 
               &(args_info->threshold_q_orig), &(args_info->threshold_q_given),
              &(local_args_info.threshold_q_given), optarg, 0, "0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "threshold_q", 'Z',
              additional_error))
            goto failure;
        
          break;
        case 'Y':	/* Fraction of datasets that must contain a gene to put it in ranking (important if individual datasets have very different gene coverage, and for datasets with small gene-size).  */
        
        
          if (update_arg( (void *)&(args_info->threshold_g_arg), 
               &(args_info->threshold_g_orig), &(args_info->threshold_g_given),
              &(local_args_info.threshold_g_given), optarg, 0, "0.50", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "threshold_g", 'Y',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Search mode: equal weighted (eq) or CV LOI (cv_loi)..  */
        
        
          if (update_arg( (void *)&(args_info->search_mode_arg), 
               &(args_info->search_mode_orig), &(args_info->search_mode_given),
              &(local_args_info.search_mode_given), optarg, cmdline_parser_search_mode_values, "NA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "search_mode", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Output directory.  */
        
        
          if (update_arg( (void *)&(args_info->dir_out_arg), 
               &(args_info->dir_out_orig), &(args_info->dir_out_given),
              &(local_args_info.dir_out_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "dir_out", 'D',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
