/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  ..\gengetopt-2.13.1\Release\gengetopt.exe -u -N -e -i Data2Sql.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->memmap_given = 0 ;
  args_info->datasets_given = 0 ;
  args_info->block_given = 0 ;
  args_info->host_given = 0 ;
  args_info->port_given = 0 ;
  args_info->database_given = 0 ;
  args_info->table_given = 0 ;
  args_info->username_given = 0 ;
  args_info->password_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_arg = NULL;
  args_info->verbosity_arg = 5 ;
  args_info->memmap_flag = 0;
  args_info->datasets_flag = 0;
  args_info->block_arg = 1000 ;
  args_info->host_arg = gengetopt_strdup ("localhost");
  args_info->port_arg = gengetopt_strdup ("3306");
  args_info->database_arg = NULL;
  args_info->table_arg = gengetopt_strdup ("datapairs");
  args_info->username_arg = gengetopt_strdup ("root");
  args_info->password_arg = NULL;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Convert multiple dat files to a single SQL table");
  printf("\nUsage: Data2Sql [OPTIONS]... [FILES]...\n\n");
  printf("%s\n","  -h, --help             Print help and exit");
  printf("%s\n","  -V, --version          Print version and exit");
  printf("%s\n","\nOptional:");
  printf("%s\n","  -i, --input=filename   Input gene mapping");
  printf("%s\n","  -v, --verbosity=INT    Message verbosity  (default=`5')");
  printf("%s\n","  -m, --memmap           Memory map input/output  (default=off)");
  printf("%s\n","  -d, --datasets         Output datasets table  (default=off)");
  printf("%s\n","  -b, --block=INT        Block size for SQL chunking  (default=`1000')");
  printf("%s\n","\nDatabase:");
  printf("%s\n","  -H, --host=STRING      Database hostname  (default=`localhost')");
  printf("%s\n","  -P, --port=STRING      Database port  (default=`3306')");
  printf("%s\n","  -D, --database=STRING  Database name");
  printf("%s\n","  -T, --table=STRING     Database table name  (default=`datapairs')");
  printf("%s\n","  -U, --username=STRING  Database username  (default=`root')");
  printf("%s\n","  -L, --password=STRING  Database password");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->host_arg)
    {
      free (args_info->host_arg); /* free previous argument */
      args_info->host_arg = 0;
    }
  if (args_info->port_arg)
    {
      free (args_info->port_arg); /* free previous argument */
      args_info->port_arg = 0;
    }
  if (args_info->database_arg)
    {
      free (args_info->database_arg); /* free previous argument */
      args_info->database_arg = 0;
    }
  if (args_info->table_arg)
    {
      free (args_info->table_arg); /* free previous argument */
      args_info->table_arg = 0;
    }
  if (args_info->username_arg)
    {
      free (args_info->username_arg); /* free previous argument */
      args_info->username_arg = 0;
    }
  if (args_info->password_arg)
    {
      free (args_info->password_arg); /* free previous argument */
      args_info->password_arg = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  if (! args_info->database_given)
    {
      fprintf (stderr, "%s: '--database' ('-D') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "verbosity",	1, NULL, 'v' },
        { "memmap",	0, NULL, 'm' },
        { "datasets",	0, NULL, 'd' },
        { "block",	1, NULL, 'b' },
        { "host",	1, NULL, 'H' },
        { "port",	1, NULL, 'P' },
        { "database",	1, NULL, 'D' },
        { "table",	1, NULL, 'T' },
        { "username",	1, NULL, 'U' },
        { "password",	1, NULL, 'L' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:v:mdb:H:P:D:T:U:L:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          if (local_args_info.version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->version_given && ! override)
            continue;
          local_args_info.version_given = 1;
          args_info->version_given = 1;
          cmdline_parser_free (&local_args_info);
          return 0;

        case 'i':	/* Input gene mapping.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* Message verbosity.  */
          if (local_args_info.verbosity_given)
            {
              fprintf (stderr, "%s: `--verbosity' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbosity_given && ! override)
            continue;
          local_args_info.verbosity_given = 1;
          args_info->verbosity_given = 1;
          args_info->verbosity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'm':	/* Memory map input/output.  */
          if (local_args_info.memmap_given)
            {
              fprintf (stderr, "%s: `--memmap' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->memmap_given && ! override)
            continue;
          local_args_info.memmap_given = 1;
          args_info->memmap_given = 1;
          args_info->memmap_flag = !(args_info->memmap_flag);
          break;

        case 'd':	/* Output datasets table.  */
          if (local_args_info.datasets_given)
            {
              fprintf (stderr, "%s: `--datasets' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->datasets_given && ! override)
            continue;
          local_args_info.datasets_given = 1;
          args_info->datasets_given = 1;
          args_info->datasets_flag = !(args_info->datasets_flag);
          break;

        case 'b':	/* Block size for SQL chunking.  */
          if (local_args_info.block_given)
            {
              fprintf (stderr, "%s: `--block' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->block_given && ! override)
            continue;
          local_args_info.block_given = 1;
          args_info->block_given = 1;
          args_info->block_arg = strtol (optarg,&stop_char,0);
          break;

        case 'H':	/* Database hostname.  */
          if (local_args_info.host_given)
            {
              fprintf (stderr, "%s: `--host' (`-H') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->host_given && ! override)
            continue;
          local_args_info.host_given = 1;
          args_info->host_given = 1;
          if (args_info->host_arg)
            free (args_info->host_arg); /* free previous string */
          args_info->host_arg = gengetopt_strdup (optarg);
          break;

        case 'P':	/* Database port.  */
          if (local_args_info.port_given)
            {
              fprintf (stderr, "%s: `--port' (`-P') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->port_given && ! override)
            continue;
          local_args_info.port_given = 1;
          args_info->port_given = 1;
          if (args_info->port_arg)
            free (args_info->port_arg); /* free previous string */
          args_info->port_arg = gengetopt_strdup (optarg);
          break;

        case 'D':	/* Database name.  */
          if (local_args_info.database_given)
            {
              fprintf (stderr, "%s: `--database' (`-D') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->database_given && ! override)
            continue;
          local_args_info.database_given = 1;
          args_info->database_given = 1;
          if (args_info->database_arg)
            free (args_info->database_arg); /* free previous string */
          args_info->database_arg = gengetopt_strdup (optarg);
          break;

        case 'T':	/* Database table name.  */
          if (local_args_info.table_given)
            {
              fprintf (stderr, "%s: `--table' (`-T') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->table_given && ! override)
            continue;
          local_args_info.table_given = 1;
          args_info->table_given = 1;
          if (args_info->table_arg)
            free (args_info->table_arg); /* free previous string */
          args_info->table_arg = gengetopt_strdup (optarg);
          break;

        case 'U':	/* Database username.  */
          if (local_args_info.username_given)
            {
              fprintf (stderr, "%s: `--username' (`-U') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->username_given && ! override)
            continue;
          local_args_info.username_given = 1;
          args_info->username_given = 1;
          if (args_info->username_arg)
            free (args_info->username_arg); /* free previous string */
          args_info->username_arg = gengetopt_strdup (optarg);
          break;

        case 'L':	/* Database password.  */
          if (local_args_info.password_given)
            {
              fprintf (stderr, "%s: `--password' (`-L') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->password_given && ! override)
            continue;
          local_args_info.password_given = 1;
          args_info->password_given = 1;
          if (args_info->password_arg)
            free (args_info->password_arg); /* free previous string */
          args_info->password_arg = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ;
    }

  return 0;

failure:
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
