/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  ..\gengetopt-2.13.1\Release\gengetopt.exe -u -N -e -i Dab2Dad.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->load_given = 0 ;
  args_info->network_given = 0 ;
  args_info->output_given = 0 ;
  args_info->answers_given = 0 ;
  args_info->directory_given = 0 ;
  args_info->mask_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->genes_given = 0 ;
  args_info->genex_given = 0 ;
  args_info->everything_given = 0 ;
  args_info->memmap_given = 0 ;
  args_info->lookup1_given = 0 ;
  args_info->lookup2_given = 0 ;
  args_info->lookups_given = 0 ;
  args_info->lookupp_given = 0 ;
  args_info->input_output_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_arg = NULL;
  args_info->load_arg = NULL;
  args_info->network_arg = NULL;
  args_info->output_arg = NULL;
  args_info->answers_arg = NULL;
  args_info->directory_arg = gengetopt_strdup (".");
  args_info->mask_arg = NULL;
  args_info->verbosity_arg = 5 ;
  args_info->genes_arg = NULL;
  args_info->genex_arg = NULL;
  args_info->everything_flag = 0;
  args_info->memmap_flag = 0;
  args_info->lookup1_arg = NULL;
  args_info->lookup2_arg = NULL;
  args_info->lookups_arg = NULL;
  args_info->lookupp_arg = NULL;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Single/multiple data file interconversion");
  printf("\nUsage: Dab2Dad [OPTIONS]... [FILES]...\n\n");
  printf("%s\n","  -h, --help                 Print help and exit");
  printf("%s\n","  -V, --version              Print version and exit");
  printf("%s\n","\n Group: input-output");
  printf("%s\n","  -i, --input=filename       Input dad file");
  printf("%s\n","  -a, --load=filename        Persistent load dad file");
  printf("%s\n","  -n, --network=filename     Input Bayesian network [x]dsl");
  printf("%s\n","\nOptional:");
  printf("%s\n","  -o, --output=filename      Output dad file");
  printf("%s\n","  -w, --answers=filename     Answer dab file");
  printf("%s\n","  -d, --directory=directory  Directory with dab files  (default=`.')");
  printf("%s\n","  -k, --mask=filename        Mask dab file");
  printf("%s\n","  -v, --verbosity=INT        Message verbosity  (default=`5')");
  printf("%s\n","  -g, --genes=filename       Gene inclusion file");
  printf("%s\n","  -G, --genex=filename       Gene exclusion file");
  printf("%s\n","  -e, --everything           Include pairs without answers  (default=off)");
  printf("%s\n","  -m, --memmap               Memory map input/output  (default=off)");
  printf("%s\n","  -l, --lookup1=STRING       First lookup gene");
  printf("%s\n","  -L, --lookup2=STRING       Second lookup gene");
  printf("%s\n","  -t, --lookups=filename     Lookup gene set");
  printf("%s\n","  -T, --lookupp=filename     Lookup pair set");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->load_arg)
    {
      free (args_info->load_arg); /* free previous argument */
      args_info->load_arg = 0;
    }
  if (args_info->network_arg)
    {
      free (args_info->network_arg); /* free previous argument */
      args_info->network_arg = 0;
    }
  if (args_info->output_arg)
    {
      free (args_info->output_arg); /* free previous argument */
      args_info->output_arg = 0;
    }
  if (args_info->answers_arg)
    {
      free (args_info->answers_arg); /* free previous argument */
      args_info->answers_arg = 0;
    }
  if (args_info->directory_arg)
    {
      free (args_info->directory_arg); /* free previous argument */
      args_info->directory_arg = 0;
    }
  if (args_info->mask_arg)
    {
      free (args_info->mask_arg); /* free previous argument */
      args_info->mask_arg = 0;
    }
  if (args_info->genes_arg)
    {
      free (args_info->genes_arg); /* free previous argument */
      args_info->genes_arg = 0;
    }
  if (args_info->genex_arg)
    {
      free (args_info->genex_arg); /* free previous argument */
      args_info->genex_arg = 0;
    }
  if (args_info->lookup1_arg)
    {
      free (args_info->lookup1_arg); /* free previous argument */
      args_info->lookup1_arg = 0;
    }
  if (args_info->lookup2_arg)
    {
      free (args_info->lookup2_arg); /* free previous argument */
      args_info->lookup2_arg = 0;
    }
  if (args_info->lookups_arg)
    {
      free (args_info->lookups_arg); /* free previous argument */
      args_info->lookups_arg = 0;
    }
  if (args_info->lookupp_arg)
    {
      free (args_info->lookupp_arg); /* free previous argument */
      args_info->lookupp_arg = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_input_output(struct gengetopt_args_info *args_info);

static void
reset_group_input_output(struct gengetopt_args_info *args_info)
{
  if (! args_info->input_output_group_counter)
    return;
  
  args_info->input_given = 0 ;
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  args_info->load_given = 0 ;
  if (args_info->load_arg)
    {
      free (args_info->load_arg); /* free previous argument */
      args_info->load_arg = 0;
    }
  args_info->network_given = 0 ;
  if (args_info->network_arg)
    {
      free (args_info->network_arg); /* free previous argument */
      args_info->network_arg = 0;
    }

  args_info->input_output_group_counter = 0;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "load",	1, NULL, 'a' },
        { "network",	1, NULL, 'n' },
        { "output",	1, NULL, 'o' },
        { "answers",	1, NULL, 'w' },
        { "directory",	1, NULL, 'd' },
        { "mask",	1, NULL, 'k' },
        { "verbosity",	1, NULL, 'v' },
        { "genes",	1, NULL, 'g' },
        { "genex",	1, NULL, 'G' },
        { "everything",	0, NULL, 'e' },
        { "memmap",	0, NULL, 'm' },
        { "lookup1",	1, NULL, 'l' },
        { "lookup2",	1, NULL, 'L' },
        { "lookups",	1, NULL, 't' },
        { "lookupp",	1, NULL, 'T' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:a:n:o:w:d:k:v:g:G:eml:L:t:T:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          if (local_args_info.version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->version_given && ! override)
            continue;
          local_args_info.version_given = 1;
          args_info->version_given = 1;
          cmdline_parser_free (&local_args_info);
          return 0;

        case 'i':	/* Input dad file.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_output_group_counter && override)
            reset_group_input_output (args_info);
          args_info->input_output_group_counter += 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          break;

        case 'a':	/* Persistent load dad file.  */
          if (local_args_info.load_given)
            {
              fprintf (stderr, "%s: `--load' (`-a') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->load_given && ! override)
            continue;
          local_args_info.load_given = 1;
          args_info->load_given = 1;
          if (args_info->input_output_group_counter && override)
            reset_group_input_output (args_info);
          args_info->input_output_group_counter += 1;
          if (args_info->load_arg)
            free (args_info->load_arg); /* free previous string */
          args_info->load_arg = gengetopt_strdup (optarg);
          break;

        case 'n':	/* Input Bayesian network [x]dsl.  */
          if (local_args_info.network_given)
            {
              fprintf (stderr, "%s: `--network' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->network_given && ! override)
            continue;
          local_args_info.network_given = 1;
          args_info->network_given = 1;
          if (args_info->input_output_group_counter && override)
            reset_group_input_output (args_info);
          args_info->input_output_group_counter += 1;
          if (args_info->network_arg)
            free (args_info->network_arg); /* free previous string */
          args_info->network_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Output dad file.  */
          if (local_args_info.output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_given && ! override)
            continue;
          local_args_info.output_given = 1;
          args_info->output_given = 1;
          if (args_info->output_arg)
            free (args_info->output_arg); /* free previous string */
          args_info->output_arg = gengetopt_strdup (optarg);
          break;

        case 'w':	/* Answer dab file.  */
          if (local_args_info.answers_given)
            {
              fprintf (stderr, "%s: `--answers' (`-w') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->answers_given && ! override)
            continue;
          local_args_info.answers_given = 1;
          args_info->answers_given = 1;
          if (args_info->answers_arg)
            free (args_info->answers_arg); /* free previous string */
          args_info->answers_arg = gengetopt_strdup (optarg);
          break;

        case 'd':	/* Directory with dab files.  */
          if (local_args_info.directory_given)
            {
              fprintf (stderr, "%s: `--directory' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->directory_given && ! override)
            continue;
          local_args_info.directory_given = 1;
          args_info->directory_given = 1;
          if (args_info->directory_arg)
            free (args_info->directory_arg); /* free previous string */
          args_info->directory_arg = gengetopt_strdup (optarg);
          break;

        case 'k':	/* Mask dab file.  */
          if (local_args_info.mask_given)
            {
              fprintf (stderr, "%s: `--mask' (`-k') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->mask_given && ! override)
            continue;
          local_args_info.mask_given = 1;
          args_info->mask_given = 1;
          if (args_info->mask_arg)
            free (args_info->mask_arg); /* free previous string */
          args_info->mask_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* Message verbosity.  */
          if (local_args_info.verbosity_given)
            {
              fprintf (stderr, "%s: `--verbosity' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbosity_given && ! override)
            continue;
          local_args_info.verbosity_given = 1;
          args_info->verbosity_given = 1;
          args_info->verbosity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'g':	/* Gene inclusion file.  */
          if (local_args_info.genes_given)
            {
              fprintf (stderr, "%s: `--genes' (`-g') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genes_given && ! override)
            continue;
          local_args_info.genes_given = 1;
          args_info->genes_given = 1;
          if (args_info->genes_arg)
            free (args_info->genes_arg); /* free previous string */
          args_info->genes_arg = gengetopt_strdup (optarg);
          break;

        case 'G':	/* Gene exclusion file.  */
          if (local_args_info.genex_given)
            {
              fprintf (stderr, "%s: `--genex' (`-G') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genex_given && ! override)
            continue;
          local_args_info.genex_given = 1;
          args_info->genex_given = 1;
          if (args_info->genex_arg)
            free (args_info->genex_arg); /* free previous string */
          args_info->genex_arg = gengetopt_strdup (optarg);
          break;

        case 'e':	/* Include pairs without answers.  */
          if (local_args_info.everything_given)
            {
              fprintf (stderr, "%s: `--everything' (`-e') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->everything_given && ! override)
            continue;
          local_args_info.everything_given = 1;
          args_info->everything_given = 1;
          args_info->everything_flag = !(args_info->everything_flag);
          break;

        case 'm':	/* Memory map input/output.  */
          if (local_args_info.memmap_given)
            {
              fprintf (stderr, "%s: `--memmap' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->memmap_given && ! override)
            continue;
          local_args_info.memmap_given = 1;
          args_info->memmap_given = 1;
          args_info->memmap_flag = !(args_info->memmap_flag);
          break;

        case 'l':	/* First lookup gene.  */
          if (local_args_info.lookup1_given)
            {
              fprintf (stderr, "%s: `--lookup1' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookup1_given && ! override)
            continue;
          local_args_info.lookup1_given = 1;
          args_info->lookup1_given = 1;
          if (args_info->lookup1_arg)
            free (args_info->lookup1_arg); /* free previous string */
          args_info->lookup1_arg = gengetopt_strdup (optarg);
          break;

        case 'L':	/* Second lookup gene.  */
          if (local_args_info.lookup2_given)
            {
              fprintf (stderr, "%s: `--lookup2' (`-L') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookup2_given && ! override)
            continue;
          local_args_info.lookup2_given = 1;
          args_info->lookup2_given = 1;
          if (args_info->lookup2_arg)
            free (args_info->lookup2_arg); /* free previous string */
          args_info->lookup2_arg = gengetopt_strdup (optarg);
          break;

        case 't':	/* Lookup gene set.  */
          if (local_args_info.lookups_given)
            {
              fprintf (stderr, "%s: `--lookups' (`-t') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookups_given && ! override)
            continue;
          local_args_info.lookups_given = 1;
          args_info->lookups_given = 1;
          if (args_info->lookups_arg)
            free (args_info->lookups_arg); /* free previous string */
          args_info->lookups_arg = gengetopt_strdup (optarg);
          break;

        case 'T':	/* Lookup pair set.  */
          if (local_args_info.lookupp_given)
            {
              fprintf (stderr, "%s: `--lookupp' (`-T') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lookupp_given && ! override)
            continue;
          local_args_info.lookupp_given = 1;
          args_info->lookupp_given = 1;
          if (args_info->lookupp_arg)
            free (args_info->lookupp_arg); /* free previous string */
          args_info->lookupp_arg = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if ( args_info->input_output_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group input-output were given. At most one is required.%s\n", argv[0], args_info->input_output_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  



  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ;
    }

  return 0;

failure:
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
