/* cmdline.h */

/* File autogenerated by gengetopt version 2.13.1  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "Funcographer"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * functions_arg;	/* Function interaction DAB.  */
  char * datasets_arg;	/* Dataset interaction DAB.  */
  char * trusts_arg;	/* Trusts PCL.  */
  char * output_arg;	/* Merged network DAB.  */
  int subgraphs_arg;	/* Number of function subgraphs to explore (default='-1').  */
  double specificity_arg;	/* Minimum initial subgraph specificity ratio (default='25').  */
  double heavy_arg;	/* Minimum final subgraph specificity fraction (default='0').  */
  int size_functions_arg;	/* Minimum size of subgraphs (default='0').  */
  int size_datasets_arg;	/* Number of associated datasets to output (default='10').  */
  int memmap_flag;	/* Memory map input (default=off).  */
  int verbosity_arg;	/* Message verbosity (default='5').  */
  int skip_arg;	/* Skip columns (default='0').  */
  double adjust_data_arg;	/* Adjustment to dataset z-scores (default='0').  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int functions_given ;	/* Whether functions was given.  */
  int datasets_given ;	/* Whether datasets was given.  */
  int trusts_given ;	/* Whether trusts was given.  */
  int output_given ;	/* Whether output was given.  */
  int subgraphs_given ;	/* Whether subgraphs was given.  */
  int specificity_given ;	/* Whether specificity was given.  */
  int heavy_given ;	/* Whether heavy was given.  */
  int size_functions_given ;	/* Whether size_functions was given.  */
  int size_datasets_given ;	/* Whether size_datasets was given.  */
  int memmap_given ;	/* Whether memmap was given.  */
  int verbosity_given ;	/* Whether verbosity was given.  */
  int skip_given ;	/* Whether skip was given.  */
  int adjust_data_given ;	/* Whether adjust_data was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
