/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef seek_rpc_CONSTANTS_H
#define seek_rpc_CONSTANTS_H

#include "seek_rpc_types.h"

namespace SeekRPC {

class seek_rpcConstants {
 public:
  seek_rpcConstants();

};

extern const seek_rpcConstants g_seek_rpc_constants;

} // namespace

#endif
