/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  ../gengetopt-2.13.1/bin/gengetopt -u -N -e -i MIer.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);


char *distance_values[] = {"pearson", "quickpear", "euclidean", "kendalls", "kolm-smir", "hypergeom", "innerprod", "bininnerprod", "mi", 0} ;	/* Possible values for distance.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->table_given = 0 ;
  args_info->memmap_given = 0 ;
  args_info->zero_given = 0 ;
  args_info->zeros_given = 0 ;
  args_info->distance_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->only_given = 0 ;
  args_info->random_given = 0 ;
  args_info->randomize_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->table_flag = 1;
  args_info->memmap_flag = 0;
  args_info->zero_flag = 0;
  args_info->zeros_arg = NULL;
  args_info->distance_arg = gengetopt_strdup ("mi");
  args_info->verbosity_arg = 5 ;
  args_info->only_arg = -1 ;
  args_info->random_arg = 0 ;
  args_info->randomize_flag = 0;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Data set pairwise mutual information calculator.");
  printf("\nUsage: MIer [OPTIONS]... [FILES]...\n\n");
  printf("%s\n","  -h, --help             Print help and exit");
  printf("%s\n","  -V, --version          Print version and exit");
  printf("%s\n","\nOptional:");
  printf("%s\n","  -t, --table            Format output as a 2D table  (default=on)");
  printf("%s\n","  -m, --memmap           Memory map input/output  (default=off)");
  printf("%s\n","  -z, --zero             Zero missing values  (default=off)");
  printf("%s\n","  -Z, --zeros=filename   Read zeroed node IDs/outputs from the given file");
  printf("%s\n","  -d, --distance=STRING  Distance measure  (possible values=\"pearson\", \n                           \"quickpear\", \"euclidean\", \"kendalls\", \n                           \"kolm-smir\", \"hypergeom\", \"innerprod\", \n                           \"bininnerprod\", \"mi\" default=`mi')");
  printf("%s\n","  -v, --verbosity=INT    Message verbosity  (default=`5')");
  printf("%s\n","  -y, --only=INT         Process only the given input file  (default=`-1')");
  printf("%s\n","  -r, --random=INT       Seed random generator  (default=`0')");
  printf("%s\n","  -R, --randomize        Assign missing values randomly  (default=off)");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->zeros_arg)
    {
      free (args_info->zeros_arg); /* free previous argument */
      args_info->zeros_arg = 0;
    }
  if (args_info->distance_arg)
    {
      free (args_info->distance_arg); /* free previous argument */
      args_info->distance_arg = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

static int
check_possible_values(const char *val, char *values[])
{
  int i, found;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return 0; /* NULL means no argument for the option */

  for (found = i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          found++;
          if (strlen(values[i]) == len)
            return 1; /* exact macth no need to check more */
        }
    }

  return found; /* return how many values are matched */
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int found = 0;
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "table",	0, NULL, 't' },
        { "memmap",	0, NULL, 'm' },
        { "zero",	0, NULL, 'z' },
        { "zeros",	1, NULL, 'Z' },
        { "distance",	1, NULL, 'd' },
        { "verbosity",	1, NULL, 'v' },
        { "only",	1, NULL, 'y' },
        { "random",	1, NULL, 'r' },
        { "randomize",	0, NULL, 'R' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVtmzZ:d:v:y:r:R", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          if (local_args_info.version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->version_given && ! override)
            continue;
          local_args_info.version_given = 1;
          args_info->version_given = 1;
          cmdline_parser_free (&local_args_info);
          return 0;

        case 't':	/* Format output as a 2D table.  */
          if (local_args_info.table_given)
            {
              fprintf (stderr, "%s: `--table' (`-t') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->table_given && ! override)
            continue;
          local_args_info.table_given = 1;
          args_info->table_given = 1;
          args_info->table_flag = !(args_info->table_flag);
          break;

        case 'm':	/* Memory map input/output.  */
          if (local_args_info.memmap_given)
            {
              fprintf (stderr, "%s: `--memmap' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->memmap_given && ! override)
            continue;
          local_args_info.memmap_given = 1;
          args_info->memmap_given = 1;
          args_info->memmap_flag = !(args_info->memmap_flag);
          break;

        case 'z':	/* Zero missing values.  */
          if (local_args_info.zero_given)
            {
              fprintf (stderr, "%s: `--zero' (`-z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->zero_given && ! override)
            continue;
          local_args_info.zero_given = 1;
          args_info->zero_given = 1;
          args_info->zero_flag = !(args_info->zero_flag);
          break;

        case 'Z':	/* Read zeroed node IDs/outputs from the given file.  */
          if (local_args_info.zeros_given)
            {
              fprintf (stderr, "%s: `--zeros' (`-Z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->zeros_given && ! override)
            continue;
          local_args_info.zeros_given = 1;
          args_info->zeros_given = 1;
          if (args_info->zeros_arg)
            free (args_info->zeros_arg); /* free previous string */
          args_info->zeros_arg = gengetopt_strdup (optarg);
          break;

        case 'd':	/* Distance measure.  */
          if (local_args_info.distance_given)
            {
              fprintf (stderr, "%s: `--distance' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if ((found = check_possible_values(optarg, distance_values)) != 1)
            {
              fprintf (stderr, "%s: %s argument, \"%s\", for option `--distance' (`-d')%s\n", argv[0], found ? "ambiguous" : "invalid", optarg, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->distance_given && ! override)
            continue;
          local_args_info.distance_given = 1;
          args_info->distance_given = 1;
          if (args_info->distance_arg)
            free (args_info->distance_arg); /* free previous string */
          args_info->distance_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* Message verbosity.  */
          if (local_args_info.verbosity_given)
            {
              fprintf (stderr, "%s: `--verbosity' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbosity_given && ! override)
            continue;
          local_args_info.verbosity_given = 1;
          args_info->verbosity_given = 1;
          args_info->verbosity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'y':	/* Process only the given input file.  */
          if (local_args_info.only_given)
            {
              fprintf (stderr, "%s: `--only' (`-y') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->only_given && ! override)
            continue;
          local_args_info.only_given = 1;
          args_info->only_given = 1;
          args_info->only_arg = strtol (optarg,&stop_char,0);
          break;

        case 'r':	/* Seed random generator.  */
          if (local_args_info.random_given)
            {
              fprintf (stderr, "%s: `--random' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->random_given && ! override)
            continue;
          local_args_info.random_given = 1;
          args_info->random_given = 1;
          args_info->random_arg = strtol (optarg,&stop_char,0);
          break;

        case 'R':	/* Assign missing values randomly.  */
          if (local_args_info.randomize_given)
            {
              fprintf (stderr, "%s: `--randomize' (`-R') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->randomize_given && ! override)
            continue;
          local_args_info.randomize_given = 1;
          args_info->randomize_given = 1;
          args_info->randomize_flag = !(args_info->randomize_flag);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ;
    }

  return 0;

failure:
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
