/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  ../gengetopt-2.13.1/bin/gengetopt -N -e -i BNConverter.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->datadir_given = 0 ;
  args_info->dataset_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->answers_given = 0 ;
  args_info->pnl_given = 0 ;
  args_info->function_given = 0 ;
  args_info->random_given = 0 ;
  args_info->randomize_given = 0 ;
  args_info->test_given = 0 ;
  args_info->iterations_given = 0 ;
  args_info->genes_given = 0 ;
  args_info->genex_given = 0 ;
  args_info->genet_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->checkpoint_given = 0 ;
  args_info->eval_train_given = 0 ;
  args_info->eval_test_given = 0 ;
  args_info->zero_given = 0 ;
  args_info->group_given = 0 ;
  args_info->murder_given = 0 ;
  args_info->elr_given = 0 ;
  args_info->default_given = 0 ;
  args_info->data_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->datadir_arg = NULL;
  args_info->dataset_arg = NULL;
  args_info->input_arg = NULL;
  args_info->output_arg = NULL;
  args_info->answers_arg = NULL;
  args_info->pnl_flag = 0;
  args_info->function_flag = 0;
  args_info->random_arg = 0 ;
  args_info->randomize_flag = 0;
  args_info->test_arg = 0 ;
  args_info->iterations_arg = 20 ;
  args_info->genes_arg = NULL;
  args_info->genex_arg = NULL;
  args_info->genet_arg = NULL;
  args_info->verbosity_arg = 5 ;
  args_info->checkpoint_flag = 0;
  args_info->eval_train_arg = NULL;
  args_info->eval_test_arg = NULL;
  args_info->zero_flag = 0;
  args_info->group_flag = 1;
  args_info->elr_flag = 0;
  args_info->default_arg = NULL;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Bayes net training and testing");
  printf("\nUsage: BNConverter [OPTIONS]...\n\n");
  printf("%s\n","  -h, --help                 Print help and exit");
  printf("%s\n","  -V, --version              Print version and exit");
  printf("%s\n","\n Group: data");
  printf("%s\n","  -d, --datadir=directory    Data directory");
  printf("%s\n","  -D, --dataset=filename     Dataset dad file");
  printf("%s\n","  -i, --input=filename       Input dsl file");
  printf("%s\n","  -o, --output=filename      Output xml file");
  printf("%s\n","  -w, --answers=filename     Answer file");
  printf("%s\n","\nOptional:");
  printf("%s\n","  -p, --pnl                  Use PNL library  (default=off)");
  printf("%s\n","  -f, --function             Use function-fitting networks  (default=off)");
  printf("%s\n","  -r, --random=INT           Seed random generator  (default=`0')");
  printf("%s\n","  -a, --randomize            Randomize CPTs before training  (default=off)");
  printf("%s\n","  -t, --test=DOUBLE          Test fraction  (default=`0')");
  printf("%s\n","  -s, --iterations=INT       EM iterations  (default=`20')");
  printf("%s\n","  -g, --genes=filename       Gene inclusion file");
  printf("%s\n","  -G, --genex=filename       Gene exclusion file");
  printf("%s\n","  -c, --genet=filename       Term inclusion file");
  printf("%s\n","  -v, --verbosity=INT        Message verbosity  (default=`5')");
  printf("%s\n","  -k, --checkpoint           Checkpoint xml file after each iteration  \n                               (default=off)");
  printf("%s\n","  -E, --eval_train=filename  Training evaluation results");
  printf("%s\n","  -e, --eval_test=filename   Test evaluation results");
  printf("%s\n","  -z, --zero                 Zero missing values  (default=off)");
  printf("%s\n","  -u, --group                Group identical inputs  (default=on)");
  printf("%s\n","  -m, --murder=INT           Kill the specified CPT before evaluation");
  printf("%s\n","  -l, --elr                  Use ELR algorithm for learning  (default=off)");
  printf("%s\n","  -b, --default=filename     Bayes net containing defaults for cases with \n                               missing data");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  if (args_info->datadir_arg)
    {
      free (args_info->datadir_arg); /* free previous argument */
      args_info->datadir_arg = 0;
    }
  if (args_info->dataset_arg)
    {
      free (args_info->dataset_arg); /* free previous argument */
      args_info->dataset_arg = 0;
    }
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->output_arg)
    {
      free (args_info->output_arg); /* free previous argument */
      args_info->output_arg = 0;
    }
  if (args_info->answers_arg)
    {
      free (args_info->answers_arg); /* free previous argument */
      args_info->answers_arg = 0;
    }
  if (args_info->genes_arg)
    {
      free (args_info->genes_arg); /* free previous argument */
      args_info->genes_arg = 0;
    }
  if (args_info->genex_arg)
    {
      free (args_info->genex_arg); /* free previous argument */
      args_info->genex_arg = 0;
    }
  if (args_info->genet_arg)
    {
      free (args_info->genet_arg); /* free previous argument */
      args_info->genet_arg = 0;
    }
  if (args_info->eval_train_arg)
    {
      free (args_info->eval_train_arg); /* free previous argument */
      args_info->eval_train_arg = 0;
    }
  if (args_info->eval_test_arg)
    {
      free (args_info->eval_test_arg); /* free previous argument */
      args_info->eval_test_arg = 0;
    }
  if (args_info->default_arg)
    {
      free (args_info->default_arg); /* free previous argument */
      args_info->default_arg = 0;
    }
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_data(struct gengetopt_args_info *args_info);

static void
reset_group_data(struct gengetopt_args_info *args_info)
{
  if (! args_info->data_group_counter)
    return;
  
  args_info->datadir_given = 0 ;
  if (args_info->datadir_arg)
    {
      free (args_info->datadir_arg); /* free previous argument */
      args_info->datadir_arg = 0;
    }
  args_info->dataset_given = 0 ;
  if (args_info->dataset_arg)
    {
      free (args_info->dataset_arg); /* free previous argument */
      args_info->dataset_arg = 0;
    }

  args_info->data_group_counter = 0;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  if (! args_info->input_given)
    {
      fprintf (stderr, "%s: '--input' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (! args_info->output_given)
    {
      fprintf (stderr, "%s: '--output' ('-o') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "datadir",	1, NULL, 'd' },
        { "dataset",	1, NULL, 'D' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "answers",	1, NULL, 'w' },
        { "pnl",	0, NULL, 'p' },
        { "function",	0, NULL, 'f' },
        { "random",	1, NULL, 'r' },
        { "randomize",	0, NULL, 'a' },
        { "test",	1, NULL, 't' },
        { "iterations",	1, NULL, 's' },
        { "genes",	1, NULL, 'g' },
        { "genex",	1, NULL, 'G' },
        { "genet",	1, NULL, 'c' },
        { "verbosity",	1, NULL, 'v' },
        { "checkpoint",	0, NULL, 'k' },
        { "eval_train",	1, NULL, 'E' },
        { "eval_test",	1, NULL, 'e' },
        { "zero",	0, NULL, 'z' },
        { "group",	0, NULL, 'u' },
        { "murder",	1, NULL, 'm' },
        { "elr",	0, NULL, 'l' },
        { "default",	1, NULL, 'b' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVd:D:i:o:w:pfr:at:s:g:G:c:v:kE:e:zum:lb:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          if (local_args_info.version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->version_given && ! override)
            continue;
          local_args_info.version_given = 1;
          args_info->version_given = 1;
          cmdline_parser_free (&local_args_info);
          return 0;

        case 'd':	/* Data directory.  */
          if (local_args_info.datadir_given)
            {
              fprintf (stderr, "%s: `--datadir' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->datadir_given && ! override)
            continue;
          local_args_info.datadir_given = 1;
          args_info->datadir_given = 1;
          if (args_info->data_group_counter && override)
            reset_group_data (args_info);
          args_info->data_group_counter += 1;
          if (args_info->datadir_arg)
            free (args_info->datadir_arg); /* free previous string */
          args_info->datadir_arg = gengetopt_strdup (optarg);
          break;

        case 'D':	/* Dataset dad file.  */
          if (local_args_info.dataset_given)
            {
              fprintf (stderr, "%s: `--dataset' (`-D') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dataset_given && ! override)
            continue;
          local_args_info.dataset_given = 1;
          args_info->dataset_given = 1;
          if (args_info->data_group_counter && override)
            reset_group_data (args_info);
          args_info->data_group_counter += 1;
          if (args_info->dataset_arg)
            free (args_info->dataset_arg); /* free previous string */
          args_info->dataset_arg = gengetopt_strdup (optarg);
          break;

        case 'i':	/* Input dsl file.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Output xml file.  */
          if (local_args_info.output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_given && ! override)
            continue;
          local_args_info.output_given = 1;
          args_info->output_given = 1;
          if (args_info->output_arg)
            free (args_info->output_arg); /* free previous string */
          args_info->output_arg = gengetopt_strdup (optarg);
          break;

        case 'w':	/* Answer file.  */
          if (local_args_info.answers_given)
            {
              fprintf (stderr, "%s: `--answers' (`-w') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->answers_given && ! override)
            continue;
          local_args_info.answers_given = 1;
          args_info->answers_given = 1;
          if (args_info->answers_arg)
            free (args_info->answers_arg); /* free previous string */
          args_info->answers_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* Use PNL library.  */
          if (local_args_info.pnl_given)
            {
              fprintf (stderr, "%s: `--pnl' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->pnl_given && ! override)
            continue;
          local_args_info.pnl_given = 1;
          args_info->pnl_given = 1;
          args_info->pnl_flag = !(args_info->pnl_flag);
          break;

        case 'f':	/* Use function-fitting networks.  */
          if (local_args_info.function_given)
            {
              fprintf (stderr, "%s: `--function' (`-f') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->function_given && ! override)
            continue;
          local_args_info.function_given = 1;
          args_info->function_given = 1;
          args_info->function_flag = !(args_info->function_flag);
          break;

        case 'r':	/* Seed random generator.  */
          if (local_args_info.random_given)
            {
              fprintf (stderr, "%s: `--random' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->random_given && ! override)
            continue;
          local_args_info.random_given = 1;
          args_info->random_given = 1;
          args_info->random_arg = strtol (optarg,&stop_char,0);
          break;

        case 'a':	/* Randomize CPTs before training.  */
          if (local_args_info.randomize_given)
            {
              fprintf (stderr, "%s: `--randomize' (`-a') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->randomize_given && ! override)
            continue;
          local_args_info.randomize_given = 1;
          args_info->randomize_given = 1;
          args_info->randomize_flag = !(args_info->randomize_flag);
          break;

        case 't':	/* Test fraction.  */
          if (local_args_info.test_given)
            {
              fprintf (stderr, "%s: `--test' (`-t') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->test_given && ! override)
            continue;
          local_args_info.test_given = 1;
          args_info->test_given = 1;
          args_info->test_arg = strtod (optarg, NULL);
          break;

        case 's':	/* EM iterations.  */
          if (local_args_info.iterations_given)
            {
              fprintf (stderr, "%s: `--iterations' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->iterations_given && ! override)
            continue;
          local_args_info.iterations_given = 1;
          args_info->iterations_given = 1;
          args_info->iterations_arg = strtol (optarg,&stop_char,0);
          break;

        case 'g':	/* Gene inclusion file.  */
          if (local_args_info.genes_given)
            {
              fprintf (stderr, "%s: `--genes' (`-g') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genes_given && ! override)
            continue;
          local_args_info.genes_given = 1;
          args_info->genes_given = 1;
          if (args_info->genes_arg)
            free (args_info->genes_arg); /* free previous string */
          args_info->genes_arg = gengetopt_strdup (optarg);
          break;

        case 'G':	/* Gene exclusion file.  */
          if (local_args_info.genex_given)
            {
              fprintf (stderr, "%s: `--genex' (`-G') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genex_given && ! override)
            continue;
          local_args_info.genex_given = 1;
          args_info->genex_given = 1;
          if (args_info->genex_arg)
            free (args_info->genex_arg); /* free previous string */
          args_info->genex_arg = gengetopt_strdup (optarg);
          break;

        case 'c':	/* Term inclusion file.  */
          if (local_args_info.genet_given)
            {
              fprintf (stderr, "%s: `--genet' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->genet_given && ! override)
            continue;
          local_args_info.genet_given = 1;
          args_info->genet_given = 1;
          if (args_info->genet_arg)
            free (args_info->genet_arg); /* free previous string */
          args_info->genet_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* Message verbosity.  */
          if (local_args_info.verbosity_given)
            {
              fprintf (stderr, "%s: `--verbosity' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbosity_given && ! override)
            continue;
          local_args_info.verbosity_given = 1;
          args_info->verbosity_given = 1;
          args_info->verbosity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'k':	/* Checkpoint xml file after each iteration.  */
          if (local_args_info.checkpoint_given)
            {
              fprintf (stderr, "%s: `--checkpoint' (`-k') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->checkpoint_given && ! override)
            continue;
          local_args_info.checkpoint_given = 1;
          args_info->checkpoint_given = 1;
          args_info->checkpoint_flag = !(args_info->checkpoint_flag);
          break;

        case 'E':	/* Training evaluation results.  */
          if (local_args_info.eval_train_given)
            {
              fprintf (stderr, "%s: `--eval_train' (`-E') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->eval_train_given && ! override)
            continue;
          local_args_info.eval_train_given = 1;
          args_info->eval_train_given = 1;
          if (args_info->eval_train_arg)
            free (args_info->eval_train_arg); /* free previous string */
          args_info->eval_train_arg = gengetopt_strdup (optarg);
          break;

        case 'e':	/* Test evaluation results.  */
          if (local_args_info.eval_test_given)
            {
              fprintf (stderr, "%s: `--eval_test' (`-e') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->eval_test_given && ! override)
            continue;
          local_args_info.eval_test_given = 1;
          args_info->eval_test_given = 1;
          if (args_info->eval_test_arg)
            free (args_info->eval_test_arg); /* free previous string */
          args_info->eval_test_arg = gengetopt_strdup (optarg);
          break;

        case 'z':	/* Zero missing values.  */
          if (local_args_info.zero_given)
            {
              fprintf (stderr, "%s: `--zero' (`-z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->zero_given && ! override)
            continue;
          local_args_info.zero_given = 1;
          args_info->zero_given = 1;
          args_info->zero_flag = !(args_info->zero_flag);
          break;

        case 'u':	/* Group identical inputs.  */
          if (local_args_info.group_given)
            {
              fprintf (stderr, "%s: `--group' (`-u') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->group_given && ! override)
            continue;
          local_args_info.group_given = 1;
          args_info->group_given = 1;
          args_info->group_flag = !(args_info->group_flag);
          break;

        case 'm':	/* Kill the specified CPT before evaluation.  */
          if (local_args_info.murder_given)
            {
              fprintf (stderr, "%s: `--murder' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->murder_given && ! override)
            continue;
          local_args_info.murder_given = 1;
          args_info->murder_given = 1;
          args_info->murder_arg = strtol (optarg,&stop_char,0);
          break;

        case 'l':	/* Use ELR algorithm for learning.  */
          if (local_args_info.elr_given)
            {
              fprintf (stderr, "%s: `--elr' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->elr_given && ! override)
            continue;
          local_args_info.elr_given = 1;
          args_info->elr_given = 1;
          args_info->elr_flag = !(args_info->elr_flag);
          break;

        case 'b':	/* Bayes net containing defaults for cases with missing data.  */
          if (local_args_info.default_given)
            {
              fprintf (stderr, "%s: `--default' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->default_given && ! override)
            continue;
          local_args_info.default_given = 1;
          args_info->default_given = 1;
          if (args_info->default_arg)
            free (args_info->default_arg); /* free previous string */
          args_info->default_arg = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if ( args_info->data_group_counter != 1)
    {
      fprintf (stderr, "%s: %d options of group data were given. One is required.%s\n", argv[0], args_info->data_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
