/* cmdline.h */

/* File autogenerated by gengetopt version 2.13.1  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "Clusterer"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * input_arg;	/* Input PCL file.  */
  char * output_arg;	/* Output DAB file.  */
  char * distance_arg;	/* Distance measure (default='quickpear').  */
  int skip_arg;	/* Columns to skip in input PCL (default='2').  */
  double diameter_arg;	/* Maximum cluster diameter (default='0.5').  */
  double diamineter_arg;	/* Minimum cluster diameter (default='0').  */
  double delta_arg;	/* Cluster diameter step size (default='0').  */
  int size_arg;	/* Minimum cluster size (default='10').  */
  int autocorrelate_flag;	/* Autocorrelate similarity measures (default=off).  */
  int normalize_flag;	/* Normalize distances before clustering (default=on).  */
  int verbosity_arg;	/* Message verbosity (default='5').  */
  int random_arg;	/* Seed random generator (default='0').  */
  char * weights_arg;	/* Input weights file.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int input_given ;	/* Whether input was given.  */
  int output_given ;	/* Whether output was given.  */
  int distance_given ;	/* Whether distance was given.  */
  int skip_given ;	/* Whether skip was given.  */
  int diameter_given ;	/* Whether diameter was given.  */
  int diamineter_given ;	/* Whether diamineter was given.  */
  int delta_given ;	/* Whether delta was given.  */
  int size_given ;	/* Whether size was given.  */
  int autocorrelate_given ;	/* Whether autocorrelate was given.  */
  int normalize_given ;	/* Whether normalize was given.  */
  int verbosity_given ;	/* Whether verbosity was given.  */
  int random_given ;	/* Whether random was given.  */
  int weights_given ;	/* Whether weights was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);

extern char *distance_values[] ;	/* Possible values for distance.  */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
