name: genomics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.*
  - matplotlib
  - scipy
  - toml
  - ipython
  - pytest
  - pytest-dependency
  - pip
  - thrift
  - pip:
    - envbash
