name: Build and Run Tests

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the
        # miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install Python Dependencies
      working-directory: ${{github.workspace}}
      # Install python libraries to "base" conda env
      run: |
        conda env update --name base --file scripts/seek/conda_environment.yml

    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install python3
        sudo apt-get install libsvm-dev
        sudo apt-get install libomp-dev
        sudo apt-get install libthrift-dev
        sudo apt-get install libgsl-dev
        sudo apt-get install libboost-dev
        sudo apt-get install libboost-graph-dev
        sudo apt-get install libboost-regex-dev
        sudo apt-get install libreadline-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/Debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/Debug --config ${{env.BUILD_TYPE}}

    # - name: C++ Tests
    #   working-directory: ${{github.workspace}}/Debug
    #   # Execute c++ based tests
    #   run: tests/unit_tests

    - name: Cache the sampleBC SEEK DB built and used by the tests
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ${{github.workspace}}/tests/test_outputs/sampleBC
        key:
          seek_cache-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{
            hashFiles('scripts/seek/seekCreateDB.py') }}-${{
            hashFiles('scripts/seek/seekUtils.py') }}

    # - name: Test Seek Utils
    #   working-directory: ${{github.workspace}}
    #   # Execute python based tests
    #   run: |
    #     # $CONDA/bin/activate base
    #     python -m pytest -s -v scripts/seek/tests/

    - name: Test Seek Tools
      working-directory: ${{github.workspace}}
      # Execute python based tests
      # python -m pytest -s -v tests/test_new2.py
      run: |
        python -m pytest -s -v tests/test_seekrpc.py
