name: Test python

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the
        # miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install Python Dependencies
      working-directory: ${{github.workspace}}
      run: |
        conda env update --name base --file scripts/seek/conda_environment.yml

    - name: Test Seek Tools
      working-directory: ${{github.workspace}}
      # Execute python based tests
      run: |
        python -m pytest -s -v tests/test_new2.py
